### PR TITLE
create bitcoin diceglyphs

### PR DESCRIPTION
**Pull request by DicetoshiNakamoto**
[meta.json](https://github.com/ordinals-wallet/ordinals-collections/files/14177188/meta.json)
[inscrptions update.json](https://github.com/ordinals-wallet/ordinals-collections/files/14177189/inscrptions.update.json)

### CODE REVIEW

**Comment by xhyhh0** [comment]
Please modify the directory and slug according to the specifications, it cannot contain spaces and uppercase letters.

**Comment by DicetoshiNakamoto** [comment]
Done, please check.

**Comment by xhyhh0** [comment]
The directory structure should be:
- bitcoin-diceglyphs
   - meta.json
   - inscriptions.json

Please delete other unrelated files and directories.

**Comment by DicetoshiNakamoto** [comment]
Done!

**Pull request merged**
